import csv, json

f = open( 'db/movies.csv', 'r')
reader = csv.DictReader( f, fieldnames = ("close","movie_title","opening_theaters","opening_day_date",
"opening_gross_amount","rank","studio","total_theaters","total_gross","year",
"title","rated","released","runtime_in_min","genre","director","writer","actors",
"plot","language","country","awards","poster","ratings","metascore","imdbrating",
"imdbvotes","imdbid","dvd","boxoffice","production","website","action","adventure",
"animation","biography","comedy","crime","documentary","drama","family","fantasy",
"film_noir","history","horror","music","musical","mystery","romance","sci-fi","short",
"sport","superhero","thriller","war","western","actors_avg_total_gross",
"actors_avg_number_of_movies","actors_avg_best_picture_gross","director_total_gross",
"director_number_of_movies","director_best_picture_gross","title_negative_sentiment",
"title_neutral_sentiment","title_positive_sentiment","title_compound_sentiment",
"poster_color","black","white","gray","red","yellow","green","cyan","blue","magenta",
"rotten_tomatoes_score"))

store = []
framenames = []

for row in reader: 
    frame = {"Closing Date": row["close"],
            "Movie Title": row["movie_title"],
            "Opening Theaters Played": row["opening_theaters"],
            "Opening Date": row["opening_day_date"],
            "Opening Gross": row["opening_gross_amount"],
            "Rank": row["rank"],
            "Studio": row["studio"],
            "Total Theaters Played": row["total_theaters"],
            "Total Gross": row["total_gross"],
            "Year": row["year"],
            "Title": row["title"],
            "Rated": row["rated"],
            "Released": row["released"],
            "Runtime in Minutes": row["runtime_in_min"],
            "Genre": row["genre"],
            "Director": row["director"],
            "Writer": row["writer"],
            "Actors": row["actors"],
            "Plot": row["plot"],
            "Language": row["language"],
            "Country": row["country"],
            "Awards": row["awards"],
            "Poster": row["poster"],
            "Ratings": row["ratings"],
            "Metascore": row["metascore"],
            "IMDb Rating": row["imdbrating"],
            "IMDb Vote Total": row["imdbvotes"],
            "IMDb ID": row["imdbid"],
            "Released to DVD": row["dvd"],
            "Box Office": row["boxoffice"],
            "Production": row["production"],
            "Website": row["website"],
            "Action": row["action"],
            "Adventure": row["adventure"],
            "Animation": row["animation"],
            "Biography": row["biography"],
            "Comedy": row["comedy"],
            "Crime": row["crime"],
            "Documentary": row["documentary"],
            "Drama": row["drama"],
            "Family": row["family"],
            "Fantasy": row["fantasy"],
            "Film Noir": row["film_noir"],
            "History": row["history"],
            "Horror": row["horror"],
            "Music": row["music"],
            "Musical": row["musical"],
            "Mystery": row["mystery"],
            "Romance": row["romance"],
            "Sci-Fi": row["sci-fi"],
            "Short": row["short"],
            "Sport": row["sport"],
            "Superhero": row["superhero"],
            "Thriller": row["thriller"],
            "War": row["war"],
            "Western": row["western"],
            "Actors Average Gross": row["actors_avg_total_gross"],
            "Actors Average Number of Movies": row["actors_avg_number_of_movies"],
            "Actors Average Best Picture Gross": row["actors_avg_best_picture_gross"],
            "Director Total Gross": row["director_total_gross"],
            "Director Number of Movies": row["director_number_of_movies"],
            "Director Best Picture Gross": row["director_best_picture_gross"],
            "Title Negative Sentiment": row["title_negative_sentiment"],
            "Title Neutral Sentiment": row["title_neutral_sentiment"],
            "Title Positive Sentiment": row["title_positive_sentiment"],
            "Title Compound Sentiment": row["title_compound_sentiment"],
            "Poster Color": row["poster_color"],
            "Black": row["black"],
            "White": row["white"],
            "Gray": row["gray"],
            "Red": row["red"],
            "Yellow": row["yellow"],
            "Green": row["green"],
            "Cyan": row["cyan"],
            "Blue": row["blue"],
            "Magenta": row["magenta"],
            "Rotten Tomatoes Score": row["rotten_tomatoes_score"]}

    if row["movie_title"] not in framenames:
        framenames.append(row["movie_title"])
        store.append(frame)

f = open( 'movies.json', 'w')

out = json.dumps(store, indent = 4)
f.write(out)